# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 10:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=50)),
                ('calories', models.IntegerField(default=500)),
                ('servings', models.IntegerField(default=1)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('fat', models.IntegerField(default=100)),
                ('protein', models.IntegerField(default=200)),
                ('carbs', models.IntegerField(default=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
