# Generated by Django 3.0.5 on 2020-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=20),
        ),
    ]
