# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20180712_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0.4),
        ),
    ]
