# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20180712_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=200),
        ),
    ]
