# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20180712_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
