# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20180714_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-create_date']},
        ),
    ]
