# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20180720_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
