# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_auto_20180731_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.IntegerField(),
        ),
    ]
