# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_auto_20180731_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
