# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('pubdate', models.CharField(max_length=100, null=True)),
                ('wikilink', models.CharField(max_length=255, null=True)),
                ('occurrences', models.IntegerField(null=True)),
            ],
        ),
    ]
