# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-07 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('publish_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postuser', to='accounts.UserModel')),
            ],
        ),
    ]
