# Generated by Django 3.0.5 on 2020-04-20 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=10)),
                ('expense_item', models.CharField(max_length=50)),
                ('expense_type', models.CharField(choices=[('Food', 'Food'), ('Bills', 'Bills'), ('Personal Care', 'Personal Care'), ('Misc', 'Misc')], default='Food', max_length=15)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
