# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('expense_type', models.CharField(choices=[('Food', 'Food'), ('Bills', 'Bills'), ('Personal Care', 'Personal Care'), ('Misc', 'Misc')], default='Food', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
