# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
