# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='item',
            new_name='expense_item',
        ),
    ]
