# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20180713_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
