# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20180714_0339'),
        ('expenses', '0004_auto_20180719_1443'),
    ]

    operations = [
    ]
