# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_merge_20180720_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Bills', 'Bills'), ('Personal Care', 'Personal Care'), ('Misc', 'Misc')], default='Food', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
