# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20180731_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_item',
            field=models.CharField(max_length=50),
        ),
    ]
