# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-01 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('occurrences', models.IntegerField()),
                ('wikilink', models.CharField(max_length=255)),
                ('amazonlink', models.CharField(max_length=255)),
            ],
        ),
    ]
