# Generated by Django 3.0.5 on 2020-04-20 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_fat', models.IntegerField(default=20)),
                ('ideal_protein', models.IntegerField(default=40)),
                ('ideal_carbs', models.IntegerField(default=40)),
                ('ideal_weight', models.IntegerField(default=185)),
                ('ideal_calories', models.IntegerField(default=2000)),
                ('current_weight', models.IntegerField(default=185)),
                ('trainer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
