# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='current_weight',
            field=models.IntegerField(default=185),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ideal_calories',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ideal_carbs',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ideal_fat',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ideal_protein',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ideal_weight',
            field=models.IntegerField(default=185),
        ),
    ]
