# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 10:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=30)),
                ('calories_burned', models.IntegerField(default=300)),
                ('exercise_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Weights', 'Weights')], default='Cardio', max_length=15)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exc_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
