# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
