# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
