# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180619_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
