# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-19 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20180711_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
