# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20180714_0245'),
        ('exercises', '0008_auto_20180719_1515'),
    ]

    operations = [
    ]
