# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20180720_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(),
        ),
    ]
