# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20180725_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
