# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20180731_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='minutes',
            field=models.IntegerField(default=30),
        ),
    ]
